<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Service Agreement_a-nzbts15v3df2</name>
   <tag></tag>
   <elementGuidId>fab65f6e-75f7-4e4e-9c5f-6de7fe2c0699</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-nzbts15v3df2&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-nzbts15v3df2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>6146a82a-b8aa-413e-9b4a-b7e33476f1be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>12605cf2-0121-4ae3-b813-d20bf90e7962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LctW5IUAAAAANo5ExmhAzbqXQpzTreb3FWPGfBP&amp;co=aHR0cDovL25ldzItd2dzaHViLnN0YWdpbmdhcHBzLm5ldDo4MA..&amp;hl=en&amp;v=PRMRaAwB3KlylGQR57Dyk-pF&amp;size=normal&amp;cb=uza3uh7hi5</value>
      <webElementGuid>0493443d-cd45-4631-830c-17ded89f70e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>697f71ed-1fc6-4066-8a29-f33e7dc9aecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>95404b8e-503f-41a3-a198-c0acab6c5221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>58a61c9c-8272-4a89-b815-f7b0093c3958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-nzbts15v3df2</value>
      <webElementGuid>77599d7a-007c-403b-bb87-ea15e6ddd42a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4bbbb779-9434-4fcf-a6c1-e40a9eaedde9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>2dec57db-c9ad-4921-9856-7df8695a75c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>80287f3a-62f5-4c1c-9b9b-7c56e9e51332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new_register&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;g-recaptcha&quot;]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>4d1afe08-db49-4add-9bcf-6cbdcc8dc80d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-nzbts15v3df2']</value>
      <webElementGuid>a79d9afe-4a1a-433c-a586-bedd84b2efc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_register']/div[11]/div/div/div/div/iframe</value>
      <webElementGuid>eddb782b-cd9a-4505-aa16-5f0aa16c69b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>18973a54-6a90-4d03-b476-9722c0b32bb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'http://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LctW5IUAAAAANo5ExmhAzbqXQpzTreb3FWPGfBP&amp;co=aHR0cDovL25ldzItd2dzaHViLnN0YWdpbmdhcHBzLm5ldDo4MA..&amp;hl=en&amp;v=PRMRaAwB3KlylGQR57Dyk-pF&amp;size=normal&amp;cb=uza3uh7hi5' and @name = 'a-nzbts15v3df2']</value>
      <webElementGuid>b8a593bc-8902-47dc-9300-f64823c30ce5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
