<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Service Agreement_a-innpjm3lj8pd</name>
   <tag></tag>
   <elementGuidId>ff23e3a2-c4b9-4efe-9d86-56856e46195d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-innpjm3lj8pd&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-innpjm3lj8pd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>de9f471c-9cc9-4568-aad5-6c3c1deafeeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>4bc5c1c3-6094-4c4e-ac65-b2df51eb6fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LctW5IUAAAAANo5ExmhAzbqXQpzTreb3FWPGfBP&amp;co=aHR0cDovL25ldzItd2dzaHViLnN0YWdpbmdhcHBzLm5ldDo4MA..&amp;hl=en&amp;v=PRMRaAwB3KlylGQR57Dyk-pF&amp;size=normal&amp;cb=yjr7ynd9lqbo</value>
      <webElementGuid>d446c20a-31d9-47e4-b1c5-64a8cde51ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>83d98f0e-666f-4759-9eff-1d2c3e1fad09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>eecffe95-40f5-430c-b218-1bf9b954b107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>f45e1013-8344-49c3-9edc-4429237c413d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-innpjm3lj8pd</value>
      <webElementGuid>3642084d-bce1-444b-bc36-d470a985f4a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e43495f2-4b03-4e58-9c37-fdb7ab519510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>feda39dd-3343-4667-ad85-55c59ff6c562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>99bcd673-5596-4bd6-9161-418088ddbcf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new_register&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;g-recaptcha&quot;]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>08fa8b9c-a47d-4770-a161-56dc76866cb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-innpjm3lj8pd']</value>
      <webElementGuid>20c727cc-90ab-4200-9b72-26dfcd94ea6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_register']/div[11]/div/div/div/div/iframe</value>
      <webElementGuid>92f7e246-913e-412c-a4a5-ff1ac5207b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>56198dd3-91ee-4690-a62e-fbca073b071d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'http://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LctW5IUAAAAANo5ExmhAzbqXQpzTreb3FWPGfBP&amp;co=aHR0cDovL25ldzItd2dzaHViLnN0YWdpbmdhcHBzLm5ldDo4MA..&amp;hl=en&amp;v=PRMRaAwB3KlylGQR57Dyk-pF&amp;size=normal&amp;cb=yjr7ynd9lqbo' and @name = 'a-innpjm3lj8pd']</value>
      <webElementGuid>101c035c-e7e8-419d-9093-d85ff550cca7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
