<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Copyright  2022 WGSHub_c-innpjm3lj8pd</name>
   <tag></tag>
   <elementGuidId>894b6a6a-587c-417f-b9ea-aa1bf973e5e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-innpjm3lj8pd&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-innpjm3lj8pd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>c3c1c39b-d04b-4e1b-ac94-8f096529af4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>recaptcha challenge expires in two minutes</value>
      <webElementGuid>e897ca99-e720-4c93-9e05-2bd105515460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=PRMRaAwB3KlylGQR57Dyk-pF&amp;k=6LctW5IUAAAAANo5ExmhAzbqXQpzTreb3FWPGfBP</value>
      <webElementGuid>4cb1870e-9773-4f02-91a6-ab3894630415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-innpjm3lj8pd</value>
      <webElementGuid>e5477b6c-b276-40a6-a787-8d5283f43fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>068447ae-8eda-40ff-abf6-562e5dab50ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>2ce8cb4e-2ea3-429d-a2a5-b26ac5791195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>3b3a2248-a68a-437b-b43b-59b15702e9e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths wf-lato-n7-active wf-lato-n4-active wf-dancingscript-n4-active wf-active&quot;]/body[@class=&quot;fixed-left&quot;]/div[3]/div[4]/iframe[1]</value>
      <webElementGuid>53f2aa82-9a7f-4a14-8e4b-452ad8e816dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-innpjm3lj8pd']</value>
      <webElementGuid>bcee7035-883b-4268-83d6-9cc925099db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/iframe</value>
      <webElementGuid>6cd3ce02-c605-439e-8774-f71224cd9aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @src = 'http://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=PRMRaAwB3KlylGQR57Dyk-pF&amp;k=6LctW5IUAAAAANo5ExmhAzbqXQpzTreb3FWPGfBP' and @name = 'c-innpjm3lj8pd']</value>
      <webElementGuid>42b95f72-e416-4e8a-9d07-ec4daf8f842b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
