<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Service Agreement_a-joowjy9aouaj</name>
   <tag></tag>
   <elementGuidId>b4f010b0-9095-4562-920c-bbbec27b5e9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-joowjy9aouaj&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-joowjy9aouaj']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>cc05faca-97e2-41a2-9f20-c2bdc521d2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>9510b2ca-3ed3-4433-98a0-98e13085b8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LctW5IUAAAAANo5ExmhAzbqXQpzTreb3FWPGfBP&amp;co=aHR0cDovL25ldzItd2dzaHViLnN0YWdpbmdhcHBzLm5ldDo4MA..&amp;hl=en&amp;v=PRMRaAwB3KlylGQR57Dyk-pF&amp;size=normal&amp;cb=jfhmw8amm977</value>
      <webElementGuid>ca26a3a2-171d-4221-a35f-fea3640c31b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>15f1f553-8e54-4087-b5a5-f88450bafea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>0b57008e-ff96-4771-901c-898401ed3a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>1f691f21-1cba-4e6a-8213-090c7ad8c460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-joowjy9aouaj</value>
      <webElementGuid>0c6a72a2-bc00-4a09-8a49-7cdd31411324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>37c3b6e7-92c6-4804-90cc-0a7b4a354bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>a3b811e1-bbc1-4027-964b-ecfe24f5ba07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>e1c189d2-09ee-4b16-a15f-8f47cc28d0c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new_register&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;g-recaptcha&quot;]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>d1f834ce-391f-417c-81ca-90f9641531b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-joowjy9aouaj']</value>
      <webElementGuid>88eac06f-5483-4f7a-98f6-346f908e8c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_register']/div[11]/div/div/div/div/iframe</value>
      <webElementGuid>4b8c81f0-174d-484f-8994-89e50f94c6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>eeabd4c7-8b8c-4659-a93a-d95a68b29101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'http://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LctW5IUAAAAANo5ExmhAzbqXQpzTreb3FWPGfBP&amp;co=aHR0cDovL25ldzItd2dzaHViLnN0YWdpbmdhcHBzLm5ldDo4MA..&amp;hl=en&amp;v=PRMRaAwB3KlylGQR57Dyk-pF&amp;size=normal&amp;cb=jfhmw8amm977' and @name = 'a-joowjy9aouaj']</value>
      <webElementGuid>ba973539-9792-4d2b-95cd-cf5236e8787b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
