<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_traffic lights_rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>62e6250d-d544-47dd-8c5d-e16907f5e37b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6ea625fe-8191-410b-a7d0-1fffd16b93d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>178ba4c9-c476-4271-9dde-54e90f771b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://www.google.com/recaptcha/api2/payload?p=06ANYolquBuN1akEI1PiCPJY44Am436Jx3arivVxu9mJqQ6cRB4DMKPPHKKFdaB_8d4BApeCNoBLfpE6Dk0ZCeCTpNk3_i2GTD6UWsCAdDWRPNCYjqlHZ51tZ6XKF_N_w7GUUBQ3-S6N0drCqQSPwG93OInemjiuC3n3ROFWBe5isTR1ZP0hgJ7EYzVgbeAQzSWTFIHuzdmPK_S29CKG6lssnUmeTuRYgYzLNyeGW7ityGfmGu8QS1-7M&amp;k=6LctW5IUAAAAANo5ExmhAzbqXQpzTreb3FWPGfBP</value>
      <webElementGuid>0c48f950-c5dd-43c7-9fd6-be480b9f3aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>0653a2e3-80fe-4b77-9cde-7c267969bccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Customer Register - WGSHub/iframe_Copyright  2022 WGSHub_c-innpjm3lj8pd</value>
      <webElementGuid>f4c547e6-fbc4-4482-9b6a-589f4b29206b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      <webElementGuid>e3a25375-8386-4c7f-b34b-2aa19010545d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'http://www.google.com/recaptcha/api2/payload?p=06ANYolquBuN1akEI1PiCPJY44Am436Jx3arivVxu9mJqQ6cRB4DMKPPHKKFdaB_8d4BApeCNoBLfpE6Dk0ZCeCTpNk3_i2GTD6UWsCAdDWRPNCYjqlHZ51tZ6XKF_N_w7GUUBQ3-S6N0drCqQSPwG93OInemjiuC3n3ROFWBe5isTR1ZP0hgJ7EYzVgbeAQzSWTFIHuzdmPK_S29CKG6lssnUmeTuRYgYzLNyeGW7ityGfmGu8QS1-7M&amp;k=6LctW5IUAAAAANo5ExmhAzbqXQpzTreb3FWPGfBP')])[6]</value>
      <webElementGuid>9faa449e-2350-4ebc-aae5-a971702824b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
      <webElementGuid>7554ed05-2dab-4183-ab7d-cee1b59b68cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://www.google.com/recaptcha/api2/payload?p=06ANYolquBuN1akEI1PiCPJY44Am436Jx3arivVxu9mJqQ6cRB4DMKPPHKKFdaB_8d4BApeCNoBLfpE6Dk0ZCeCTpNk3_i2GTD6UWsCAdDWRPNCYjqlHZ51tZ6XKF_N_w7GUUBQ3-S6N0drCqQSPwG93OInemjiuC3n3ROFWBe5isTR1ZP0hgJ7EYzVgbeAQzSWTFIHuzdmPK_S29CKG6lssnUmeTuRYgYzLNyeGW7ityGfmGu8QS1-7M&amp;k=6LctW5IUAAAAANo5ExmhAzbqXQpzTreb3FWPGfBP']</value>
      <webElementGuid>2da49f1d-2cc1-4dd0-8301-c2db03529e73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
