<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Name cant be blank</name>
   <tag></tag>
   <elementGuidId>d3e48274-7657-419e-b36a-f5cbd3507286</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#register_name-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='register_name-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>54c980be-e42d-4baf-84f3-2a9ca511fe0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>register_name-error</value>
      <webElementGuid>172e6ef5-ff0e-448a-aed2-c5a96e71ea0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help-block text-danger</value>
      <webElementGuid>7f15668e-7f5f-4ef1-8143-cdc1f66cfaff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>register_name</value>
      <webElementGuid>a0ec5ffc-9c54-4524-9d9a-90836bd34d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name can't be blank</value>
      <webElementGuid>ca7018ce-b490-4c73-b567-4cca5aedfe60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register_name-error&quot;)</value>
      <webElementGuid>c22049f2-7225-4316-9c94-00f6f977ff39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='register_name-error']</value>
      <webElementGuid>482adc15-4ff0-40d6-a8fd-8dc814ecd8ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_register']/div/label[2]</value>
      <webElementGuid>d4943c01-8870-4c21-8ea2-510a36eefc76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name*'])[1]/following::label[1]</value>
      <webElementGuid>e33ef78b-4901-4c2e-a51a-d7d0c1e0a0f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='One step closer to your digital solutions'])[1]/following::label[2]</value>
      <webElementGuid>475100ea-647c-41b3-90c9-7b6e63bddd5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/preceding::label[1]</value>
      <webElementGuid>9b662ad5-f827-4022-ba20-c263c51c56fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email*'])[1]/preceding::label[2]</value>
      <webElementGuid>b423c610-6d64-4921-98b1-e07cafab14a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>cc7d76dc-17c6-4228-b8db-14ab1976c9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'register_name-error' and (text() = concat(&quot;Name can&quot; , &quot;'&quot; , &quot;t be blank&quot;) or . = concat(&quot;Name can&quot; , &quot;'&quot; , &quot;t be blank&quot;))]</value>
      <webElementGuid>6b74cc4a-c3a7-4c9e-a38d-4ec8860dc7ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
