<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Would you like to get update on WGS te_e37c52</name>
   <tag></tag>
   <elementGuidId>d6534942-d385-4dbc-b798-2353b63ff13c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.checkmark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='new_register']/div[10]/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>40498ecf-6272-4374-a492-df25d11d812b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>a6eb6250-67f9-4e0f-bf69-0db64f5c5300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new_register&quot;)/div[@class=&quot;agreement&quot;]/label[@class=&quot;checkbox-custom&quot;]/span[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>f674e201-9abc-4bdf-94aa-fdb81265bef2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_register']/div[10]/label/span</value>
      <webElementGuid>c2d73776-afbb-468d-ac27-3052c313de61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>ac683867-68bd-4c3f-a9f4-2694906d41d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
