<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Register here</name>
   <tag></tag>
   <elementGuidId>def6d99f-e218-47df-9c78-44dc761d68d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.register-section > div > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form_login']/form/div[3]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ba3ba3ba-2cec-4d39-b999-c6c87d39d134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/registers</value>
      <webElementGuid>38059626-fd3a-4a98-a140-f1d1d969c11a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register here</value>
      <webElementGuid>e0cd31f6-0658-46f5-bc48-b936720bef86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_login&quot;)/form[1]/div[@class=&quot;register-section&quot;]/div[1]/a[1]</value>
      <webElementGuid>f68d9e4a-0586-42ea-9c7c-c2877e859801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e7045785-0a02-41a3-bab3-d109d1eb29f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/registers</value>
      <webElementGuid>25b340c3-06dc-435d-9389-3fb22df1756e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register here</value>
      <webElementGuid>bd04fbe0-d470-4460-8ea0-126cf407292b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_login&quot;)/form[1]/div[@class=&quot;register-section&quot;]/div[1]/a[1]</value>
      <webElementGuid>fb681a55-4563-4325-b17d-fa39280b77e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_login']/form/div[3]/div/a</value>
      <webElementGuid>ac036e1b-1115-4a77-91a1-2fea41dda069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Register here')]</value>
      <webElementGuid>a5a419ae-7859-4884-8133-b604b07442a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/following::a[1]</value>
      <webElementGuid>94feb81c-b9d1-4b0e-b0f7-89131a6a1b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2022 WGSHub.'])[1]/preceding::a[1]</value>
      <webElementGuid>a08ae382-b619-4386-a20a-3d9ffaf5c031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Register here']/parent::*</value>
      <webElementGuid>12d5246c-99c8-414e-a5a0-c0a12f8d1f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/registers')]</value>
      <webElementGuid>40752074-d044-41da-8932-df95fcddd086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>48c8b809-8fa4-4b72-8875-0f4b07f4a1d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/registers' and (text() = 'Register here' or . = 'Register here')]</value>
      <webElementGuid>2ea9c35e-5fbf-4ad0-98ca-cc596d8a45fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
