<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Read More</name>
   <tag></tag>
   <elementGuidId>b1103089-e5de-4244-9e84-e888b5cd7301</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list_solutions']/div/div[2]/div/div[2]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6df817aa-fed7-4389-a28d-17f0dfbd2450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button-rounded button-primary</value>
      <webElementGuid>72111eb8-16a2-4f4d-b6e7-d2ebee2fdd91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/solutions/ui-uxs</value>
      <webElementGuid>85f642db-a039-457b-8975-49c57a6c6356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Read More</value>
      <webElementGuid>230f52cb-6bed-444b-9a1a-dc3a293f277c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_solutions&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;portfolio-item-wrap&quot;]/div[@class=&quot;portfolio-text-wrap&quot;]/a[@class=&quot;button button-rounded button-primary&quot;]</value>
      <webElementGuid>855502fa-d368-4475-a828-1ffaa6c40802</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_solutions']/div/div[2]/div/div[2]/a[2]</value>
      <webElementGuid>291bc694-fc82-4912-86a4-490376a40335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Read More')])[2]</value>
      <webElementGuid>857d48ed-1c5b-4f7a-9e93-4e63c1f9aec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UI / UX Design Service'])[1]/following::a[2]</value>
      <webElementGuid>98bdb468-27d6-405d-acf8-ab34eb7892a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product'])[1]/following::a[2]</value>
      <webElementGuid>dac18210-fad2-4833-b1c5-fad94d549916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Case Study'])[2]/preceding::a[1]</value>
      <webElementGuid>d47536cb-077e-4140-b1e0-6bd7e29b181e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/solutions/ui-uxs')])[2]</value>
      <webElementGuid>8dc8ace0-0018-4144-a981-992975e6cb9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/a[2]</value>
      <webElementGuid>ed9a29b3-88c6-40ed-bb38-cd2a07415e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/solutions/ui-uxs' and (text() = 'Read More' or . = 'Read More')]</value>
      <webElementGuid>80af4b1d-6c05-4e29-affa-7316f2cb5344</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
