<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Find what you need_p</name>
   <tag></tag>
   <elementGuidId>4620dd2e-5b2b-4ae1-a90a-ffeec8a3b0b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.search-filter > #p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='p'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c32d0193-ab9c-4dd4-835f-ef5d62e72f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>771355a5-cfa3-4cbc-be32-ea922b4fb8b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c1b26e78-d7dd-4d4b-8a94-6bcfd4550f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>db7153ad-c9f5-4f10-b481-3fb2984b1eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Keyword, technology, etc  ...</value>
      <webElementGuid>11b31041-721f-4b09-a2c8-bf8553e5466e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sm-form-control</value>
      <webElementGuid>2a674a0c-4c76-406e-b099-253a64bd1ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side-panel&quot;)/div[@class=&quot;scwStickySidebar&quot;]/div[@class=&quot;side-panel-wrap&quot;]/form[@id=&quot;form_search&quot;]/div[@class=&quot;search-form-group&quot;]/div[@class=&quot;search-filter&quot;]/input[@id=&quot;p&quot;]</value>
      <webElementGuid>0a337bcd-0715-4d18-b75b-46d6af9d2b10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='p'])[2]</value>
      <webElementGuid>54522187-c96f-45ac-8f34-8cd2ec3f5b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_search']/div/div/input</value>
      <webElementGuid>b748ed6a-db31-441d-b94b-fcd5e25c573b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>3571a807-1a09-47b5-9588-6a896ce4f27c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @name = 'p' and @id = 'p' and @placeholder = 'Keyword, technology, etc  ...']</value>
      <webElementGuid>8f5e0785-0886-4495-a77d-2a4507534f30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
