<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Consulting</name>
   <tag></tag>
   <elementGuidId>781b7dfc-efc1-45d8-8448-d12fa9a4a5b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.checkbox-style-3-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form_search']/div[2]/div/div[2]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a7bc67de-9994-4166-852d-d8386c49a93d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-style-3-label</value>
      <webElementGuid>78fc6111-6077-4b51-a8c9-a09552303b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>filter-Consulting</value>
      <webElementGuid>ab685294-5c44-466b-9ef0-6c6219b19901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Consulting</value>
      <webElementGuid>4a32ace4-4170-481d-8d5f-d910e7f76112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side-panel&quot;)/div[@class=&quot;scwStickySidebar&quot;]/div[@class=&quot;side-panel-wrap&quot;]/form[@id=&quot;form_search&quot;]/div[@class=&quot;checkbox-filter&quot;]/div[@class=&quot;toggle&quot;]/div[@class=&quot;togglec&quot;]/div[@class=&quot;checkbox-grup&quot;]/label[@class=&quot;checkbox-style-3-label&quot;]</value>
      <webElementGuid>9b070f08-bb15-4fd1-a63b-520dabff4744</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_search']/div[2]/div/div[2]/div/label</value>
      <webElementGuid>cc4d4592-de8e-4e20-98b3-174ee09fe334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solution Type'])[1]/following::label[1]</value>
      <webElementGuid>1a347895-ae10-4a68-87ed-787dfc9f98a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valuation'])[1]/preceding::label[1]</value>
      <webElementGuid>694ac086-94f1-43e6-abce-fcff744cad58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Consulting']/parent::*</value>
      <webElementGuid>b4541908-1bbc-46e6-8004-87d30c9aca4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>fdd04c71-21cf-473b-a663-679c153404dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Consulting' or . = 'Consulting')]</value>
      <webElementGuid>e1ba2d25-5180-4a1f-b577-b885b1164d73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
