<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_As seen on_media-item</name>
   <tag></tag>
   <elementGuidId>e6ae1a5a-2933-4116-9aa4-2b8cba47abde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div[3]/div/div/div/div/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3a59ccc8-43bd-4f08-a93d-7014f3e580d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>media-item</value>
      <webElementGuid>671cc514-3993-4489-a5d2-654113c3a92d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://finance.detik.com/bursa-dan-valas/d-5832263/bei-bakal-kedatangan-calon-emiten-teknologi-lepas-208-juta-saham</value>
      <webElementGuid>b466e821-278c-4f71-b859-be901a40a8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>dbce5dc2-e0f3-425d-aef4-e65d75485970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>finance.detik.com</value>
      <webElementGuid>d1dc2ed6-eb2f-4b8c-8477-d2980aa79dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;section nobg nomargin new-media-coverage&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;media-coverage-wrapper&quot;]/div[@class=&quot;media-coverage-items&quot;]/a[@class=&quot;media-item&quot;]</value>
      <webElementGuid>717ec242-7cd4-4a97-98e6-b4576ce41143</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div[3]/div/div/div/div/div/a[2]</value>
      <webElementGuid>0d8988c2-b48d-4ff0-83ad-b210e38d13bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='As seen on :'])[1]/following::a[2]</value>
      <webElementGuid>cdca975a-7386-494c-95f7-f3557092d636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read more'])[6]/following::a[2]</value>
      <webElementGuid>618af0fb-10ea-4b72-b7cf-49f476d08522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Info'])[1]/preceding::a[7]</value>
      <webElementGuid>e852cd92-5730-493e-ac8d-245ba9846699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='investor.relation@wgshub.com'])[1]/preceding::a[7]</value>
      <webElementGuid>55826a87-a18d-4145-b901-799cf54b9628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://finance.detik.com/bursa-dan-valas/d-5832263/bei-bakal-kedatangan-calon-emiten-teknologi-lepas-208-juta-saham')]</value>
      <webElementGuid>883aad67-7b35-4bb5-86e2-52cc0b85b836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a[2]</value>
      <webElementGuid>33b0bfbb-81f7-4a62-9b97-1b8077dd844f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://finance.detik.com/bursa-dan-valas/d-5832263/bei-bakal-kedatangan-calon-emiten-teknologi-lepas-208-juta-saham' and @title = 'finance.detik.com']</value>
      <webElementGuid>c0acd0ea-34f7-4034-8765-4bdbbe2eac73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
