<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_corpsecwgshub.com_social-item social-linkedin</name>
   <tag></tag>
   <elementGuidId>5bc12b94-bbc0-4944-ab8c-a8f73f01582e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.social-item.social-linkedin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='copyrights']/div/a[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0d26e248-cb15-496e-9e5b-b619b105f446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>social-item social-linkedin</value>
      <webElementGuid>26a298f7-a8a8-4d0a-b034-92155ffd9a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.linkedin.com/company/11338213</value>
      <webElementGuid>325f5e39-1b41-433e-9cbf-832a407789a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>f57ae8b5-440f-4476-ab24-be8469ffc334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;copyrights&quot;)/div[@class=&quot;footer-social-wrap&quot;]/a[@class=&quot;social-item social-linkedin&quot;]</value>
      <webElementGuid>0828f9f4-0b83-48fd-a051-9eb1be5f99d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='copyrights']/div/a[4]</value>
      <webElementGuid>ddf43a1f-670a-4a6e-a250-04a858ce8b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='corpsec@wgshub.com'])[1]/following::a[4]</value>
      <webElementGuid>14f48cb1-c01f-4e62-961a-f90a903f4783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='investor.relation@wgshub.com'])[1]/following::a[5]</value>
      <webElementGuid>6f54792d-57cc-433d-b69f-f44b9aa3effa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright ©2021 PT Wira Global Solusi Tbk. All Rights Reserved'])[1]/preceding::a[2]</value>
      <webElementGuid>14c61f21-e1b4-4c77-93e9-7edb5f2ca8fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.linkedin.com/company/11338213')]</value>
      <webElementGuid>646b848d-dd18-478d-94ce-837c0ae6981b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a[4]</value>
      <webElementGuid>cab0355c-b013-469e-b446-961cf7628a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.linkedin.com/company/11338213']</value>
      <webElementGuid>d8f314a4-b300-49c4-a1d9-9f6c69807af8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
