<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_LEARN MORE</name>
   <tag></tag>
   <elementGuidId>7e971de8-9291-48ec-9f22-9c5ae8b8f03d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.btn-banner > a.button.button-rounded.button-outline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='content']/div/div[4]/div/div[2]/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2a768560-4dbe-4f71-8b42-ae658822dd14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button-rounded button-outline</value>
      <webElementGuid>aa7b6ae6-103a-42b2-98f0-09dd80cd301b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/solutions</value>
      <webElementGuid>b0805fff-d9ec-4fe7-9858-ab7076ea1813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Learn More</value>
      <webElementGuid>93d148cb-8be2-49b0-9372-f0123379b90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;content-wrap page-new-home nopadding&quot;]/div[@class=&quot;section nomargin&quot;]/div[@class=&quot;row banner-row&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;text-banner&quot;]/div[@class=&quot;btn-banner&quot;]/a[@class=&quot;button button-rounded button-outline&quot;]</value>
      <webElementGuid>083e6960-baf6-4ad9-b701-f573c6fd817e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>38b4fd8d-21d2-465b-961e-e087ca8a9949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button-rounded button-outline</value>
      <webElementGuid>80856db8-3c16-41b1-9ec6-73178a67ea9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.mythologicstudio.com/</value>
      <webElementGuid>b485da27-52e5-4f7d-a6ff-1f399aa7f29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>2e38d656-e6e1-4123-83e3-1b4a7d31f1b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LEARN MORE</value>
      <webElementGuid>72e42f0d-78b6-4934-a7e8-7f105965bedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ventures-list&quot;)/div[@class=&quot;col-md-3&quot;]/div[@class=&quot;startup-item&quot;]/div[@class=&quot;startup-text&quot;]/a[@class=&quot;button button-rounded button-outline&quot;]</value>
      <webElementGuid>91a6043f-9ad0-4b7b-9b26-53ca3f6ed8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b0b5524f-d3f7-46fb-a1a7-ae4b9ede8aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button-rounded button-outline</value>
      <webElementGuid>ea44368f-565b-4bd4-a9bc-24bb9a35a996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/solutions</value>
      <webElementGuid>c32353ee-496e-430e-be07-3c074e0b3620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Learn More</value>
      <webElementGuid>e73547f1-728a-4925-8da5-ee77f2f4cb63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;content-wrap page-new-home nopadding&quot;]/div[@class=&quot;section nomargin&quot;]/div[@class=&quot;row banner-row&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;text-banner&quot;]/div[@class=&quot;btn-banner&quot;]/a[@class=&quot;button button-rounded button-outline&quot;]</value>
      <webElementGuid>a781ff5f-6b43-4fbf-ad3f-83ef867ab1eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a1d17304-876d-4bae-ac2f-aff4cc2a0196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button-rounded button-outline</value>
      <webElementGuid>95c9bf0e-cf0c-4ab2-a72d-10389b12b81b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/solutions</value>
      <webElementGuid>f67fffd6-f6d0-413f-ae4d-7b1fd2c684a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Learn More</value>
      <webElementGuid>64c0b629-b481-47ca-ae5e-db582a99462a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;content-wrap page-new-home nopadding&quot;]/div[@class=&quot;section nomargin&quot;]/div[@class=&quot;row banner-row&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;text-banner&quot;]/div[@class=&quot;btn-banner&quot;]/a[@class=&quot;button button-rounded button-outline&quot;]</value>
      <webElementGuid>ceb1b8c7-9092-4034-9b46-7154c9424504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c39cb169-2cc5-4c1a-8eeb-d83a7b39f17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button-rounded button-outline</value>
      <webElementGuid>50d4081d-6d54-4b81-a710-dad3ccf6b6f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.mythologicstudio.com/</value>
      <webElementGuid>db64473c-c05a-466f-bdd0-b793ec3f4ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>ac25eb2d-e103-4669-b067-6933ecd4c033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LEARN MORE</value>
      <webElementGuid>8052ef91-1d21-4423-a704-76a5d9119d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ventures-list&quot;)/div[@class=&quot;col-md-3&quot;]/div[@class=&quot;startup-item&quot;]/div[@class=&quot;startup-text&quot;]/a[@class=&quot;button button-rounded button-outline&quot;]</value>
      <webElementGuid>84c1cc4a-ed67-4426-8ba8-97d43c961d76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/div/div[4]/div/div[2]/div/div[2]/a</value>
      <webElementGuid>570ea0b6-a0bd-45c2-b18c-34e0274ffefe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Learn More')]</value>
      <webElementGuid>9c9245bc-1cf5-4d81-9ed1-a0cf004d353d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We have a complete Tech Ecosystem'])[1]/following::a[1]</value>
      <webElementGuid>5a63ba0e-7eb7-440d-9c89-fffd7124cfae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='»'])[1]/following::a[1]</value>
      <webElementGuid>7d31b233-f32e-4672-a900-18799e187c2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rare beast'])[1]/preceding::a[1]</value>
      <webElementGuid>551163b0-8c56-4017-b553-2749ea7776de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Learn More']/parent::*</value>
      <webElementGuid>c5838bd8-489e-423f-8ead-6da3f95f17a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/solutions')])[2]</value>
      <webElementGuid>8a6d0c21-59bf-4ef0-b8fc-a0f348555a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/a</value>
      <webElementGuid>805c5d3c-e7d7-4296-9ba5-dbc13c699b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/solutions' and (text() = 'Learn More' or . = 'Learn More')]</value>
      <webElementGuid>565e51c9-aa6d-48b7-b806-213e7a901c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ventures-list']/div[2]/div/div/a</value>
      <webElementGuid>963be146-8cec-415b-8869-d65205d8145f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'LEARN MORE')]</value>
      <webElementGuid>5f528297-f81f-43c3-aa23-6d573a59454c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mythologic Studio'])[1]/following::a[1]</value>
      <webElementGuid>75f4aba4-1546-4ec1-8888-062c0b9bbd9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TALENT MORE'])[1]/following::a[1]</value>
      <webElementGuid>66fcdfe8-eb09-4647-ac7a-70e38fffbebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAGII'])[1]/preceding::a[1]</value>
      <webElementGuid>de18776f-ac8b-4479-8d8e-868504b42cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DOWNLOAD APP'])[1]/preceding::a[1]</value>
      <webElementGuid>565f0e70-ca3f-4f1b-8247-5d95944404c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LEARN MORE']/parent::*</value>
      <webElementGuid>8741d8a1-42a2-4333-9788-0c9baeefffd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.mythologicstudio.com/')]</value>
      <webElementGuid>eaffff8e-0a25-4786-bd5f-0990b161bc0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a</value>
      <webElementGuid>0ecb8a29-81e2-475e-8b0c-25cbd5f0866c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.mythologicstudio.com/' and (text() = 'LEARN MORE' or . = 'LEARN MORE')]</value>
      <webElementGuid>dc5228b4-bee0-4dd0-8065-3d469027e382</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
