<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Newsroom</name>
   <tag></tag>
   <elementGuidId>d07000d0-ecc1-497b-814d-630f3ba5e128</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.sub-menu.sfHover > ul > li.sfHover > a > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='primary-menu']/ul/li[7]/ul/li/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7ac0ae4f-044a-4733-a043-0a8928d17390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Newsroom</value>
      <webElementGuid>d9178b33-846e-47dd-aa2d-c98a774f49cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primary-menu&quot;)/ul[@class=&quot;sf-js-enabled&quot;]/li[@class=&quot;sub-menu sfHover&quot;]/ul[1]/li[@class=&quot;sfHover&quot;]/a[1]/div[1]</value>
      <webElementGuid>85554584-e435-4525-a5ee-7154f2bea2f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='primary-menu']/ul/li[7]/ul/li/a/div</value>
      <webElementGuid>63491782-4084-4c3b-a793-256daa7e4a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Media Room'])[1]/following::div[1]</value>
      <webElementGuid>b06f8560-0cec-41f7-8663-3f64ea78b5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SDG'])[1]/following::div[2]</value>
      <webElementGuid>a5bbb855-5396-4bb7-aebe-520a962570fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publications'])[1]/preceding::div[1]</value>
      <webElementGuid>2ea0c245-8355-4108-b9d8-4f12081d5dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Career'])[1]/preceding::div[2]</value>
      <webElementGuid>faab5a1d-7f6d-4d07-80a5-a531aa436c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Newsroom']/parent::*</value>
      <webElementGuid>2a1e9d38-8435-4775-b88f-90644706d1f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/ul/li/a/div</value>
      <webElementGuid>4f9700ff-6169-4e12-ad28-31d8d5a15ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Newsroom' or . = 'Newsroom')]</value>
      <webElementGuid>982aaa08-4a50-4bd8-80bc-72e07aa5f7f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
