<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Publications</name>
   <tag></tag>
   <elementGuidId>5e8299da-701e-446a-959d-eac58185c021</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.sub-menu.sfHover > ul > li.sfHover > a > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='primary-menu']/ul/li[7]/ul/li[2]/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b6ff5993-d927-4ed7-95ca-e323d71fb8a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Publications</value>
      <webElementGuid>0bc36d43-b3d5-4bd2-940c-bfb3ff466023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primary-menu&quot;)/ul[@class=&quot;sf-js-enabled&quot;]/li[@class=&quot;sub-menu sfHover&quot;]/ul[1]/li[@class=&quot;sfHover&quot;]/a[1]/div[1]</value>
      <webElementGuid>34986f6e-87dc-4343-91be-791e87a27b3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='primary-menu']/ul/li[7]/ul/li[2]/a/div</value>
      <webElementGuid>77951e6c-6f43-4184-a4ce-0014ac2b4079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Newsroom'])[1]/following::div[1]</value>
      <webElementGuid>b3cf444f-5f3b-4c7c-a817-7144cdccb69d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Media Room'])[1]/following::div[2]</value>
      <webElementGuid>fc93b80a-ba0d-4fd0-903b-08c556706124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Career'])[1]/preceding::div[1]</value>
      <webElementGuid>6333657d-1b58-464a-b377-1c7781fd0b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/preceding::div[2]</value>
      <webElementGuid>e43fe033-3d9e-4612-887d-d23055ed4a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Publications']/parent::*</value>
      <webElementGuid>e673993c-bebe-43b0-ac60-0251df53101c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/ul/li[2]/a/div</value>
      <webElementGuid>437547a5-26eb-4b75-a5e4-acd95d22155d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Publications' or . = 'Publications')]</value>
      <webElementGuid>5cea7030-72ee-4a90-b982-4a0ceecccd61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
