<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_History</name>
   <tag></tag>
   <elementGuidId>9fc68e74-f452-434d-9d43-0349c9794ee3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.sub-menu.sfHover > ul > li.sfHover > a > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='primary-menu']/ul/li[2]/ul/li[3]/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>59cefb7d-1488-423a-8b8f-17057dced3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>History</value>
      <webElementGuid>05df7ec5-7152-4204-a37f-f396229bb109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primary-menu&quot;)/ul[@class=&quot;sf-js-enabled&quot;]/li[@class=&quot;sub-menu sfHover&quot;]/ul[1]/li[@class=&quot;sfHover&quot;]/a[1]/div[1]</value>
      <webElementGuid>0407319a-f803-47f4-ba90-e6afd4f74b2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='primary-menu']/ul/li[2]/ul/li[3]/a/div</value>
      <webElementGuid>44361fe2-d9fe-4541-9c98-ba98fd56eb20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Core Values'])[1]/following::div[1]</value>
      <webElementGuid>4aca45e5-6210-4cab-a7ad-80a610fd62ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vision Mission'])[1]/following::div[2]</value>
      <webElementGuid>88d44566-8a19-4166-8340-eb696cfc8cff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organization Structure'])[1]/preceding::div[1]</value>
      <webElementGuid>88c012eb-19e0-4fbe-84f9-18dd7ead25fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subsidiaries'])[1]/preceding::div[2]</value>
      <webElementGuid>055f4b17-be15-423c-b9c4-acd19ba99984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='History']/parent::*</value>
      <webElementGuid>b5803414-a791-4361-8272-d84bc0476adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[3]/a/div</value>
      <webElementGuid>596254f7-7ebd-478f-a952-b743a772377f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'History' or . = 'History')]</value>
      <webElementGuid>fc5843b0-7f22-4fed-be9d-901d299777b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
