<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Read more</name>
   <tag></tag>
   <elementGuidId>dedf66e1-2029-48fd-a6b4-64fb30396ba4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='content']/div/div[6]/div/div[2]/div[2]/div[2]/a/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>34c0dce4-9e9d-431e-92d2-d993169550f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>read-more-overlay</value>
      <webElementGuid>2b96916d-ba26-41ca-a9db-84fa161f5473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Read more</value>
      <webElementGuid>efb7949d-c0e9-42e1-87fe-c81cc1b14608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;content-wrap page-new-home nopadding&quot;]/div[@class=&quot;section nomargin home-recent-news&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;home-publications-wrap&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/a[@class=&quot;article-item&quot;]/div[@class=&quot;featured_image&quot;]/div[@class=&quot;read-more-overlay&quot;]</value>
      <webElementGuid>ab9dc153-31cf-4dff-88f4-cfcd7bc0e532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1e6cb124-8612-4018-abb4-c546da982ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>read-more-overlay</value>
      <webElementGuid>726477c5-fac2-4bbf-92b3-ec478e0f4f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Read more</value>
      <webElementGuid>6bc81f8b-009a-4be0-9c77-31e7edb8a8ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;content-wrap page-new-home nopadding&quot;]/div[@class=&quot;section nomargin home-recent-news&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;home-news-wrap&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/a[@class=&quot;article-item&quot;]/div[@class=&quot;featured_image&quot;]/div[@class=&quot;read-more-overlay&quot;]</value>
      <webElementGuid>fec8c49c-2b06-4c17-98b4-1845ce8338cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>237788e5-60b5-4ba4-9abf-9e9371b742d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>read-more-overlay</value>
      <webElementGuid>3995b4db-1b93-4e18-b5a3-e40c60bdbc93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Read more</value>
      <webElementGuid>d2602f72-57ad-4096-bf52-92a4e2140d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;content-wrap page-new-home nopadding&quot;]/div[@class=&quot;section nomargin home-recent-news&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;home-publications-wrap&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/a[@class=&quot;article-item&quot;]/div[@class=&quot;featured_image&quot;]/div[@class=&quot;read-more-overlay&quot;]</value>
      <webElementGuid>9a90f980-ab04-4a28-b4fe-f9fd1272bb0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>46a29796-3e90-476d-96a2-59f669b38e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>read-more-overlay</value>
      <webElementGuid>2e1576a0-6ff3-4387-bb5d-304d68eb451e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Read more</value>
      <webElementGuid>60d3e1c4-6417-493a-83fd-637595c419dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;content-wrap page-new-home nopadding&quot;]/div[@class=&quot;section nomargin home-recent-news&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;home-news-wrap&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/a[@class=&quot;article-item&quot;]/div[@class=&quot;featured_image&quot;]/div[@class=&quot;read-more-overlay&quot;]</value>
      <webElementGuid>ed0c4588-74b2-4914-8933-94bb7c9a546e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/div/div[6]/div/div[2]/div[2]/div[2]/a/div[2]/div</value>
      <webElementGuid>ea5b5416-731d-4490-bb0a-954a76eb42b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jun'])[1]/following::div[2]</value>
      <webElementGuid>a3eea22f-088e-4d0f-9404-f057bb3a10fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah Venture Builder dan Bagaimana Cara Kerjanya?'])[1]/following::div[6]</value>
      <webElementGuid>b77cd485-5be3-4d9a-9c13-7c224ddec81f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apr'])[1]/preceding::div[2]</value>
      <webElementGuid>bad7625f-b1a5-4fc2-bd4f-097e064a218a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read more'])[6]/preceding::div[4]</value>
      <webElementGuid>95f68bdf-fab2-4642-bb17-ed68b6791f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/a/div[2]/div</value>
      <webElementGuid>b5097759-fd89-4e66-acd6-adbfbb7749c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Read more' or . = 'Read more')]</value>
      <webElementGuid>c4dfa60c-4807-4b27-89ca-e08bc59992b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/div/div[6]/div/div/div[2]/div/a/div[2]/div</value>
      <webElementGuid>3686e8d8-5857-4c38-a923-5a373597df65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aug'])[1]/following::div[2]</value>
      <webElementGuid>d2907741-ed57-473f-85eb-76ae102465ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See All News'])[1]/following::div[7]</value>
      <webElementGuid>34160c41-997f-4cc3-b13b-9684c96e4f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WGSHub: The Road to Public Listed Company'])[1]/preceding::div[1]</value>
      <webElementGuid>8e6d34db-633b-4ff8-9f91-1494e740e393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='May'])[1]/preceding::div[2]</value>
      <webElementGuid>f4e5b656-fe70-460b-8061-8d569df93e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Read more']/parent::*</value>
      <webElementGuid>c561a9e8-d292-41f4-8535-90c8b0aaea04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]/div</value>
      <webElementGuid>0310f22f-b96f-4a96-bce9-64a6926029ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
