<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Subsidiaries</name>
   <tag></tag>
   <elementGuidId>90dcd6b1-aba4-4066-a71f-157f741979c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.sub-menu.sfHover > ul > li.sfHover > a > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='primary-menu']/ul/li[2]/ul/li[5]/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c5fa9f03-5b21-4f7c-a721-9cc8a21d6bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subsidiaries</value>
      <webElementGuid>a9da0572-4de7-4880-8319-4f806b2cea15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primary-menu&quot;)/ul[@class=&quot;sf-js-enabled&quot;]/li[@class=&quot;sub-menu sfHover&quot;]/ul[1]/li[@class=&quot;sfHover&quot;]/a[1]/div[1]</value>
      <webElementGuid>52a3c7e1-70aa-4c09-bb6e-15c5aa607c87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='primary-menu']/ul/li[2]/ul/li[5]/a/div</value>
      <webElementGuid>001b658f-b9ad-4b66-bfda-92af61f97adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organization Structure'])[1]/following::div[1]</value>
      <webElementGuid>bcf9b487-c896-4036-ab25-7e61ff07eb82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='History'])[1]/following::div[2]</value>
      <webElementGuid>5a2a958c-41ad-443e-804f-e8e9971f3d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ecosystem'])[1]/preceding::div[1]</value>
      <webElementGuid>521d40dc-74d9-4f53-a093-b2954c8d6650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Governance'])[1]/preceding::div[2]</value>
      <webElementGuid>774daa4c-3377-4356-a574-6f733cc19912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Subsidiaries']/parent::*</value>
      <webElementGuid>3227dbd0-57a3-4d46-ae30-23f236b833ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[5]/a/div</value>
      <webElementGuid>d59fa753-2ca7-450f-865d-d029ff720d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Subsidiaries' or . = 'Subsidiaries')]</value>
      <webElementGuid>d18b0e4c-09dc-4c8d-9434-846313f92887</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
