<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Copyright 2021 PT Wira Global Solusi Tb_93d427</name>
   <tag></tag>
   <elementGuidId>d33344d1-cdd2-41aa-9e4c-2bb0a1cdda6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gotoTop</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gotoTop']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ce02c0a8-d073-49a9-88f5-26166bb965c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-angle-up</value>
      <webElementGuid>edb3e9d1-1476-40cf-8caa-7e72c6e82516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gotoTop</value>
      <webElementGuid>db17cb41-dc84-49e0-b819-f3b3c9502a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gotoTop&quot;)</value>
      <webElementGuid>279608ae-ccfa-4e27-9e6c-7b96296c773f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='gotoTop']</value>
      <webElementGuid>6619df56-efb9-43a9-92b8-eb207924464f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>e42978f0-8d2f-4b1b-a471-7a09a0abf567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'gotoTop']</value>
      <webElementGuid>634a75c8-a878-4858-9a59-2cde5a5134a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
